# Generated by Django 2.1.5 on 2019-01-06 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('user', 'identifier')},
        ),
    ]
