# Generated by Django 2.1.5 on 2019-01-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20190106_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('integration', 'integration_artist_id')},
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('artist', 'integration_release_id')},
        ),
    ]
